cesmii/main -> cesmii/develop
cesmii/CESMII-CloudLibrary pull request #47
Opened 2023-08-22 17:55 UTC by scoxen1

Merge the urgent fix made to Cloud Library cosmetics back into develop branch. May require some merging actions.

2023-09-04 15:08 UTC, scoxen1 commented
@MarkusHorstmann   - When you have a chance, can you review? This is all of the UI/UX changes that were deployed to main that we want to get back into our develop branch.

2023-09-05 20:00 UTC, MarkusHorstmann approved these changes

2023-09-05 20:03 UTC, MarkusHorstmann requested changes
Everything looks good. Just need to fix whitespace/formatting issues caught by the dotnet_format action:
D:\a\CESMII-CloudLibrary\CESMII-CloudLibrary\UACloudLibraryServer\Areas\Identity\Pages\Account\Register.cshtml.cs(112,123): error WHITESPACE: Fix whitespace formatting. Insert '\s'.
D:\a\CESMII-CloudLibrary\CESMII-CloudLibrary\UACloudLibraryServer\SendGridEmailSender.cs(53,55): error WHITESPACE: Fix whitespace formatting. Insert '\s'.

2023-09-07 14:27 UTC, scoxen1 commented
> Everything looks good. Just need to fix whitespace/formatting issues caught by the dotnet_format action: D:\a\CESMII-CloudLibrary\CESMII-CloudLibrary\UACloudLibraryServer\Areas\Identity\Pages\Account\Register.cshtml.cs(112,123): error WHITESPACE: Fix whitespace formatting. Insert '\s'. D:\a\CESMII-CloudLibrary\CESMII-CloudLibrary\UACloudLibraryServer\SendGridEmailSender.cs(53,55): error WHITESPACE: Fix whitespace formatting. Insert '\s'.

@MarkusHorstmann - I corrected the issues.

2023-09-07 17:05 UTC, MarkusHorstmann approved these changes

2023-09-07 17:05 UTC, merged